---
title: "multiSim"
author: "Jonathan Cordell"
date: "17/02/2022"
output: 
  pdf_document:
    pandoc_args: --listings
    includes:
      in_header: preamble.tex
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(tidy.opts=list(width.cutoff=60),tidy=TRUE)
library(ggplot2)
library(knitr)
```

```{r, include=FALSE}
source("sim.R")$value
```

```{r, include=FALSE}
default.classSize <- 30
default.noYears <- 6
default.subjectTeachers <- 0
default.maxTime <- 100
#Rate of infection + background
default.backgroundROI <- 3300/67000000 
default.gammaParams <- c("spread.shape"=10,"spread.scale"=0.8,"recover.shape"=17,"recover.scale"=0.8)
default.testType <- "Lateral"
default.probs <- list("Lateral"=list("TP"=47/100,"TN"=99850/99900),"PCR"=list("TP"=67/100,"TN"=99.2/100), "None"=list("TP"=0,"TN"=1))
default.quarantineTime=10
default.catchRate <- 0.9
default.testDays <- c(5,0)
default.startingInfected <- 5
default.quarantineThreshold <- 30
default.teacherInfective <- 3
default.teacherInfectible <- 1.5
default.teacherTeacher <- 1.5
default.nonClass <- 0.7
default.weekend <- c(0.3,10)
default.maxIPeriod <- 20
default.percVacc <- 0.3
default.vaccEff <- list("spread"=0.3,"catch"=0.2)
default.whoMask <- c("s","t")
default.maskEff <- 0.15
```
```{r, include=FALSE}
findAvg <- function(classSize=default.classSize,noYears=default.noYears,subjectTeachers=default.subjectTeachers,maxTime=default.maxTime,backgroundROI=default.backgroundROI,gammaParams=default.gammaParams,testType=default.testType,probs=default.probs,quarantineTime=default.quarantineTime,catchRate=default.catchRate,testDays=default.testDays,startingInfected=default.startingInfected,quarantineThreshold=default.quarantineThreshold,teacherInfective=default.teacherInfective,teacherInfectible=default.teacherInfectible,teacherTeacher=default.teacherTeacher,nonClass=default.nonClass,weekend=default.weekend,maxIPeriod=default.maxIPeriod,percVacc=default.percVacc,vaccEff=default.vaccEff,whoMask=default.whoMask,maskEff=default.maskEff, runs=10){
  summary<-NULL
  populations<-data.frame("S"=rep(0,maxTime),"I"=rep(0,maxTime),"Q"=rep(0,maxTime),"R"=rep(0,maxTime))
  for (i in 1:runs){
    res <- sim(classSize, noYears, subjectTeachers, maxTime, backgroundROI, gammaParams, testType, probs, quarantineTime, catchRate, testDays, startingInfected, quarantineThreshold, teacherInfective, teacherInfectible, teacherTeacher, nonClass, weekend, maxIPeriod, percVacc, vaccEff, whoMask, maskEff)
    summary<-rbind(summary,res$summary)
    populations<-populations+res$populations
  }
  result <- list("summary"=data.frame(t(colMeans(summary))),"populations"=populations/10)
  return(result)
}  
```


```{r, warning=FALSE, message=FALSE, echo=FALSE}
str<-("Base case parameters:")
str<-paste(str,paste("Class size of",default.classSize),"\n",sep="")
str<-paste(str,paste(default.noYears,"years in the school"),"\n",sep="")
str<-paste(str,paste(default.subjectTeachers,"subject teachers"),"\n",sep="")
str<-paste(str,paste("Simulation runs for",default.maxTime,"time steps"),"\n",sep="")
str<-paste(str,paste("Background Rate of Infection of",default.backgroundROI),"\n",sep="")
str<-paste(str,paste("Individuals viral load over time modelled as gamma distribution with shape",default.gammaParams["spread.shape"],"and scale",default.gammaParams["spread.scale"]),"\n",sep="")
str<-paste(str,paste("Individuals probability of recovering over time modelled as gamma distribution with shape",default.gammaParams["recover.shape"],"and scale",default.gammaParams["recover.scale"]),"\n",sep="")
str<-paste(str,paste("Testing type is",default.testType,"which has true positive rate of",default.probs[[default.testType]]$TP,"and true negative rate of",default.probs[[default.testType]]$TN),"\n",sep="")
str<-paste(str,paste("Testing is done on days",toString(default.testDays)),"\n",sep="")
str<-paste(str,paste("Time spent quarantining is",default.quarantineTime,"days"),"\n",sep="")
str<-paste(str,paste("The base probability of catching the disease is",default.catchRate),"\n",sep="")
str<-paste(str,paste("Starting number of infected is",default.startingInfected),"\n",sep="")
str<-paste(str,paste("Threshold of quarantining individuals considered noteworthy is",default.quarantineThreshold),"\n",sep="")
str<-paste(str,paste("Teacher to their student infection multiplier set to", default.teacherInfective),"\n",sep="")
str<-paste(str,paste("Student to their teacher infection multiplier set to", default.teacherInfectible),"\n",sep="")
str<-paste(str,paste("Teacher to teacher infection multiplier set to", default.teacherTeacher),"\n",sep="")
str<-paste(str,paste("Infection multiplier for students in seperate classes set to",  default.nonClass),"\n",sep="")
str<-paste(str,paste("During weekends, probability of infection from school is multiplied by",default.weekend[1],"whilst infection from other sources is multiplied by",default.weekend[2]),"\n",sep="")
str<-paste(str,paste("The maximum possible time to be infectious is taken to be", default.maxIPeriod),"\n",sep="")
str<-paste(str,paste("It is taken that",(default.percVacc*100),"people are vaccinated, which is",(100*default.vaccEff$spread),"percent effective at reducing the spread from a vaccinated infected individual, and",(100*default.vaccEff$catch),"percent effective at reducing that chance of catching the disease"),"\n")
str<-paste(str,paste("We assume that the",toString(default.whoMask),"groups are mandated to wear masks, which is ",(100*default.maskEff),"percent effective at reducing transmission"),"\n")
cat(str)
```

```{r}
popPlot<-function(data, label){
  barplot(t(as.matrix(data)), col=c("cyan","yellow", "grey","red"), xlab="Days", ylab="Individuals", names.arg=(1:nrow(data)),main=label)
  legend("topright", colnames(data), fill=c("cyan","yellow", "grey","red"), bg="white")
}
```

```{r}
baseCase<-findAvg(runs=3)
test<-findAvg(runs=3,percVacc=0)
test2<-findAvg(runs=3,vaccEff=list("spread"=0.7,"catch"=0.6))
test3<-findAvg(runs=3,percVacc=0.7)
test4<-findAvg(runs=3,maskEff=1)
test5<-findAvg(runs=3,whoMask=c("none"))
test6<-findAvg(runs=3,testType = "PCR", testDays=c(-1))
test7<-findAvg(runs=3,testType = "None")


results <- cbind(name="Base Case",baseCase$summary)
results <- rbind(results,cbind(name="No Vacc",test$summary))
results <- rbind(results,cbind(name="More Effective Vacc",test2$summary))
results <- rbind(results,cbind(name="More Vacc",test3$summary))
results <- rbind(results,cbind(name="100% mask Eff",test4$summary))
results <- rbind(results,cbind(name="No Masks",test5$summary))
results <- rbind(results,cbind(name="PCR 1 p/w",test6$summary))
results <- rbind(results,cbind(name="No Test",test7$summary))
```


```{r}
kable(t(results))
```

```{r, fig.show="hold", out.width="50%"}
popPlot(baseCase$populations,"Base Case")
popPlot(test$populations,"No Vacc")
popPlot(test2$populations,"More Effective Vacc")
popPlot(test3$populations,"More Vacc")
popPlot(test4$populations,"100% mask Eff")
popPlot(test5$populations,"No Masks")
popPlot(test6$populations,"PCR 1 p/w")
popPlot(test7$populations,"No Test")
```